### ISSUE TITLE
author list

### ISSUE THREAD

**Issue by vrooje** [vrooje/gzcandels_datapaper#11]
- [x] collaborators who've commented on past drafts
- [x] GZ-CANDELS builders (both collabs)
- [x] overall CANDELS builders
- [x] GOODS-S photometric catalog builders
- [x] COSMOS photometric catalog builders
- [x] UDS photometric catalog builders
- [x] GOODS-S specz builders
- [x] COSMOS specz builders
- [x] UDS specz builders
- [x] GOODS-S photometric redshift builders
- [x] COSMOS photometric redshift builders
- [x] UDS photometric redshift builders
- [x] CANDELS team visual classification builders
- [x] Bulge/Disk decomposition builders

**Comment by vrooje** [comment]
@BorisHaeussler on that last item - who besides you should be an author on this basis?

**Comment by BorisHaeussler** [comment]
Hi Brooke,
Sorry, first observing run, very stressful here, not much time.

I think there's a few people who should be on because they made the images (e.g. Anton) and others, but I guess they will be on your paper anyway.
As for the B/D decomposition catalogue directly (builders), I don't think there needs to be anyone but myself. The software is all finished developed and public, and I was the only one involved in running it on CANDELS, really.

I had some help from (again) Anton (images) and Arjen vdWel (clarifying a few things regarding sigma images and/or PSF).
I also used PSFs made by Liz McGrath and yourself, so if you feel that you should be on that for that reason, Liz should be, too.

How's San Diego?

Boris

> On 4 Dec 2015, at 20:37, Brooke Simmons notifications@github.com wrote:
> 
> @BorisHaeussler https://github.com/BorisHaeussler on that last item - who besides you should be an author on this basis?
> 
> —
> Reply to this email directly or view it on GitHub https://github.com/vrooje/gzcandels_datapaper/issues/11#issuecomment-162110638.

---

Boris Häußler
European Southern Observatory
Alonso de Cordova 3107
Vitacura, Santiago, Chile
Boris.Haeussler@eso.org mailto:bhaeussl@eso.org
BorisHaeussler.astro@gmail.com mailto:BorisHaeussler.astro@gmail.com

---
