### ISSUE TITLE
Further checking for errant bots

### ISSUE THREAD

**Issue by willettk** [vrooje/gzcandels_datapaper#29]
Did we look at the CANDELS classifications for signs of errant/non-human behavior aside from the star/artifact question? If so, would it be quick to run? I think it'd be good if we had the ability to write a sentence in 3.4 akin to "We have also analyzed the percentages of the remaining top-level categories (smooth and features/disk) for all users and find no/some/lots of evidence for bot-based classifications".

**Comment by vrooje** [comment]
I initially tried to find the set of classifiers who had the same path through the tree X% of the time, whatever that path was -- but in the end I realised the T00-only method was much faster and the consensus-based weighting would take care of classifiers who have either random or otherwise significantly deviant paths anyway, so T00 was the main issue I needed to deal with. If there's no statement about the consensus-based weighting dealing with other weird behaviour, I agree it should be added...

Overall though I do think we should be checking for bots earlier, and probably automatically as part of an overall project health check on all Zooniverse projects...

**Comment by willettk** [comment]
Yeah - that's reasonable. What about just the top level, though? Did we
look for users who selected smooth or features/disk >99% of the time?

**Comment by vrooje** [comment]
Among those who submitted at least 200 classifications, 0 classifiers answered a-1 (features/disk) >98% of the time, and 2 classifiers answered a-0 (smooth) >98% of the time; the rest of the single-answer classifiers were star/artifact, so either pretty unsophisticated bots or tourists.

**Comment by willettk** [comment]
I think that'd be a sentence worth reporting.

**Comment by vrooje** [comment]
Should already be there? S3.7 Paragraph 3, though I didn't mention that 0 bots were detected that preferred a-1.

**Comment by willettk** [comment]
Ah yes (S3.4, actually). Totally missed that the first time around.
